---
app:
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5432/demodb"
    password: password
    poll-size: 30
    username: postgres
flyway:
  baselineOnMigrate: true
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: mypass
debug: true